author_show_all:
  path: /author/all
  controller: App\Controller\AuthorApiController::showAll
  methods: GET|HEAD

author_create:
  path: /author/create
  controller: App\Controller\AuthorApiController::create
  methods: POST

author_find_by_name:
  path: /author/find
  controller: App\Controller\AuthorApiController::findByName
  methods: POST

book_show_all:
  path: /book/all
  controller: App\Controller\BookApiController::showAll
  methods: GET|HEAD

book_show:
  path: /{_locale}/book/{id}
  controller: App\Controller\BookApiController::show
  requirements:
        _locale: en|ru
  methods: GET|HEAD

book_search_by_name:
  path: /book/search/{text}
  controller: App\Controller\BookApiController::searchByName
  methods: GET|HEAD

book_create:
  path: /book/create
  controller: App\Controller\BookApiController::create
  methods: POST

